# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gupiao2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1258, 861)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(110, 40, 1081, 781))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.PageDownButtonA = QtWidgets.QPushButton(self.tab)
        self.PageDownButtonA.setGeometry(QtCore.QRect(340, 680, 126, 33))
        self.PageDownButtonA.setObjectName("PageDownButtonA")
        self.KpictureA = QtWidgets.QGraphicsView(self.tab)
        self.KpictureA.setGeometry(QtCore.QRect(500, 300, 551, 261))
        self.KpictureA.setObjectName("KpictureA")
        self.PageUpButtonA = QtWidgets.QPushButton(self.tab)
        self.PageUpButtonA.setGeometry(QtCore.QRect(200, 680, 126, 33))
        self.PageUpButtonA.setObjectName("PageUpButtonA")
        self.lineEditBA = QtWidgets.QLineEdit(self.tab)
        self.lineEditBA.setGeometry(QtCore.QRect(650, 570, 271, 41))
        self.lineEditBA.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditBA.setObjectName("lineEditBA")
        self.inquireButtonA = QtWidgets.QPushButton(self.tab)
        self.inquireButtonA.setGeometry(QtCore.QRect(720, 610, 126, 33))
        self.inquireButtonA.setObjectName("inquireButtonA")
        self.textEditA = QtWidgets.QTextEdit(self.tab)
        self.textEditA.setGeometry(QtCore.QRect(500, 40, 551, 251))
        self.textEditA.setObjectName("textEditA")
        self.tableWidgetA = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetA.setGeometry(QtCore.QRect(0, 0, 471, 681))
        self.tableWidgetA.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidgetA.setRowCount(15)
        self.tableWidgetA.setColumnCount(2)
        self.tableWidgetA.setObjectName("tableWidgetA")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetA.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetA.setHorizontalHeaderItem(1, item)
        self.tableWidgetA.horizontalHeader().setDefaultSectionSize(218)
        self.tableWidgetA.verticalHeader().setDefaultSectionSize(43)
        self.tableWidgetA.verticalHeader().setMinimumSectionSize(33)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.PageDownButtonB = QtWidgets.QPushButton(self.tab_2)
        self.PageDownButtonB.setGeometry(QtCore.QRect(340, 680, 126, 33))
        self.PageDownButtonB.setObjectName("PageDownButtonB")
        self.KpictureB = QtWidgets.QGraphicsView(self.tab_2)
        self.KpictureB.setGeometry(QtCore.QRect(500, 300, 551, 261))
        self.KpictureB.setObjectName("KpictureB")
        self.PageUpButtonB = QtWidgets.QPushButton(self.tab_2)
        self.PageUpButtonB.setGeometry(QtCore.QRect(200, 680, 126, 33))
        self.PageUpButtonB.setObjectName("PageUpButtonB")
        self.lineEditB = QtWidgets.QLineEdit(self.tab_2)
        self.lineEditB.setGeometry(QtCore.QRect(650, 570, 271, 41))
        self.lineEditB.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditB.setObjectName("lineEditB")
        self.inquireButtonB = QtWidgets.QPushButton(self.tab_2)
        self.inquireButtonB.setGeometry(QtCore.QRect(720, 610, 126, 33))
        self.inquireButtonB.setObjectName("inquireButtonB")
        self.textEditB = QtWidgets.QTextEdit(self.tab_2)
        self.textEditB.setGeometry(QtCore.QRect(500, 40, 551, 251))
        self.textEditB.setObjectName("textEditB")
        self.tableWidgetB = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetB.setGeometry(QtCore.QRect(0, 0, 471, 681))
        self.tableWidgetB.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidgetB.setRowCount(15)
        self.tableWidgetB.setColumnCount(2)
        self.tableWidgetB.setObjectName("tableWidgetB")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetB.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetB.setHorizontalHeaderItem(1, item)
        self.tableWidgetB.horizontalHeader().setDefaultSectionSize(218)
        self.tableWidgetB.verticalHeader().setDefaultSectionSize(43)
        self.tableWidgetB.verticalHeader().setMinimumSectionSize(33)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "股票"))
        self.PageDownButtonA.setText(_translate("Form", "下一页"))
        self.PageUpButtonA.setText(_translate("Form", "上一页"))
        self.lineEditBA.setText(_translate("Form", "请按代码查询"))
        self.inquireButtonA.setText(_translate("Form", "查询"))
        item = self.tableWidgetA.horizontalHeaderItem(0)
        item.setText(_translate("Form", "代码"))
        item = self.tableWidgetA.horizontalHeaderItem(1)
        item.setText(_translate("Form", "简称"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "沪深A股"))
        self.PageDownButtonB.setText(_translate("Form", "下一页"))
        self.PageUpButtonB.setText(_translate("Form", "上一页"))
        self.lineEditB.setText(_translate("Form", "请按代码查询"))
        self.inquireButtonB.setText(_translate("Form", "查询"))
        item = self.tableWidgetB.horizontalHeaderItem(0)
        item.setText(_translate("Form", "代码"))
        item = self.tableWidgetB.horizontalHeaderItem(1)
        item.setText(_translate("Form", "简称"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "沪深B股"))

